### PR TITLE
Date parsing that is looser and stricter.

### PR DESCRIPTION
**Pull request by otfrom**
It allows for a space between date and time in addition to T as
suggested in the text of the RFC.

It also limits months, days of the month, hours, minutes and seconds to
reasonable numbers. It doesn't yet try to parse things, but it keeps the
strings closer to real ISO Date Times.

### CODE REVIEW

**Comment by zeeshanlakhani** [comment]
I'm def. :+1: on this. @jeremyheiler and @bowmanb ... want to review before we :shipit: ?

**Comment by jeremyheiler** [comment]
This looks great. :+1:

**Comment by zeeshanlakhani** [comment]
Cool. I'll merge later today and update on clojars.

**Comment by otfrom** [comment]
Thx! Glad to hear it is helpful. I'm looking forward to using it.

**Comment by zeeshanlakhani** [comment]
@otfrom merged and 1.5 is up on clojars.

**Comment by otfrom** [comment]
Thx!

**Pull request merged**
